env:
  node: true

extends:
  [
    'eslint:recommended',
    'plugin:react/recommended',
    'plugin:react/jsx-runtime',
    'plugin:import/recommended',
    'plugin:import/typescript',
    'plugin:jsx-a11y/recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:@typescript-eslint/recommended-requiring-type-checking',
    'eslint-config-prettier',
    'plugin:etc/recommended',
  ]

parser: '@typescript-eslint/parser'

parserOptions:
  project: './tsconfig.json'

plugins:
  - react
  - import
  - jsx-a11y
  - '@typescript-eslint'
  - etc

root: true

settings:
  react:
    version: 'detect'

  'import/resolver':
    node:
      paths: ['src']
      extensions: ['.js', '.jsx', '.ts', '.tsx']

    typescript:
      alwaysTryTypes: true
      project: './tsconfig.json'

  'import/parsers':
    '@typescript-eslint/parser': ['.ts', '.tsx']

rules:
  '@typescript-eslint/no-unsafe-assignment': warn
  no-console:
    - warn
    - allow:
        - warn
        - error
  '@typescript-eslint/no-unused-vars':
    ['warn', { 'argsIgnorePattern': '^_', 'varsIgnorePattern': '^_' }]
  '@typescript-eslint/no-unsafe-enum-comparison': off
  '@typescript-eslint/no-misused-promises':
    - error
    - checksVoidReturn: false
  react/jsx-sort-props:
    - warn
    - ignoreCase: true
  no-restricted-imports:
    - warn
    - paths:
        - name: react-router-dom
          importNames:
            - useNavigate
          message: "Please use 'useTrackedNavigate' instead."
  '@typescript-eslint/no-explicit-any': 'off'
  eqeqeq:
    - warn
    - always
